#!/bin/sh
#
# Tests for the GIFLIB utilities.
# Usage:
#	visual-check [display_prgm]
#
#   This test assumes the gif_lib utilities are available from one of the
# path directories, and that GIF_DIR is set (directly or through command line)
# to the directory holding these gif files:
# 1. solid2.gif
# 2. gifgrid.gif
# 3. porsche.gif
#   In addition, set GIF_DISPLAY (directly or through command line) to the
# program to display GIFs on our system.
#
# Gershon Elber, Feb 90.  Rewritten by Eric Raymond, December 1995.
# Revised by Toshio Kuratomi December 1998.
# Used to be called test-unx.
PATH=$PATH:../util
GIF_DIR=../pic
GIF_DISPLAY=${1:-"display -"}

echo "Announce the test"
gifecho -t "The GIFLIB test sequence begins" | giftool -d 250 | $GIF_DISPLAY

echo "The Porsche."
$GIF_DISPLAY <$GIF_DIR/porsche.gif

echo "Color histogram of the Porsche image"
gifhisto -b -s 200 512 $GIF_DIR/porsche.gif | $GIF_DISPLAY

echo "The GIF grid graphic"
$GIF_DISPLAY <$GIF_DIR/gifgrid.gif

echo "The grid graphic, reconstructed from its RGB dump (should look identical)"
gif2rgb <$GIF_DIR/gifgrid.gif | gif2rgb -s 100 100 | $GIF_DISPLAY
